### ISSUE TITLE
README.md: passing token as a param doesn't work

### ISSUE THREAD

**Issue by markiz** [flowcommerce/ruby-sdk#6]
See https://github.com/flowcommerce/ruby-sdk/blob/5f2c219dc87185ee024a2965346010a085f37638/README.md#installation

> FlowCommerce.instance(:token => "<YOUR API TOKEN>")

This doesn't work as the only ways to pass the token are env var, env var pointing to the file and `~/.flow/token`.

From my perspective it might make sense to actually allow that, but you could change the doc instead. #

**Comment by mbryzek** [comment]
Fixed by https://github.com/flowcommerce/ruby-sdk/pull/7

**Comment by markiz** [comment]
👍
